# Generated by Django 5.2.2 on 2025-06-07 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del negocio')),
                ('slug', models.SlugField(help_text='URL única: tuapp.com/este-slug/', unique=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Período de prueba'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('EXPIRED', 'Expirado')], default='TRIAL', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('BASIC', 'Básico'), ('PROFESSIONAL', 'Profesional'), ('ENTERPRISE', 'Empresarial')], default='BASIC', max_length=20)),
                ('primary_color', models.CharField(default='#007bff', help_text='Color primario en formato hex', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.tenant')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
    ]
