# Generated by Django 5.2.2 on 2025-06-08 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_table_alter_order_table_number'),
        ('restaurants', '0002_table_tablescanlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, verbose_name='ID de empleado')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('on_break', 'En descanso'), ('busy', 'Ocupado')], default='active', max_length=20)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible para notificaciones')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Recibir emails')),
                ('notification_push', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='Sonido de notificación')),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='Inicio de turno')),
                ('shift_end', models.TimeField(blank=True, null=True, verbose_name='Fin de turno')),
                ('total_orders_served', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.PositiveIntegerField(default=0, help_text='En minutos')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garzón',
                'verbose_name_plural': 'Garzones',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('restaurant', 'user')},
            },
        ),
        migrations.AddField(
            model_name='table',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to='restaurants.waiter', verbose_name='Garzón asignado'),
        ),
        migrations.CreateModel(
            name='WaiterNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'Nuevo pedido'), ('order_ready', 'Pedido listo'), ('customer_request', 'Solicitud del cliente'), ('table_call', 'Llamada de mesa'), ('urgent', 'Urgente')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('read', 'Leído'), ('responded', 'Respondido'), ('dismissed', 'Descartado')], default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1, help_text='1=Normal, 2=Alta, 3=Urgente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.waiter')),
            ],
            options={
                'verbose_name': 'Notificación de Garzón',
                'verbose_name_plural': 'Notificaciones de Garzones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['waiter', 'status'], name='restaurants_waiter__d14d9a_idx'), models.Index(fields=['created_at'], name='restaurants_created_34fb85_idx'), models.Index(fields=['notification_type'], name='restaurants_notific_52b6b3_idx')],
            },
        ),
    ]
