# Generated by Django 5.2.2 on 2025-06-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_waiter_table_assigned_waiter_waiternotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, help_text='ej: mirestaurante.com (opcional, para QRs personalizados)', max_length=255, null=True, verbose_name='Dominio personalizado'),
        ),
    ]
