# Generated by Django 5.2.2 on 2025-06-10 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_tenant_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='average_completion_time',
            field=models.PositiveIntegerField(default=0, help_text='En minutos'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='total_tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BarStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, verbose_name='ID de empleado')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('on_break', 'En descanso'), ('busy', 'Ocupado')], default='active', max_length=20)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible para notificaciones')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Recibir emails')),
                ('notification_push', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='Sonido de notificación')),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='Inicio de turno')),
                ('shift_end', models.TimeField(blank=True, null=True, verbose_name='Fin de turno')),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('average_completion_time', models.PositiveIntegerField(default=0, help_text='En minutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('drink_specialties', models.JSONField(blank=True, default=list, help_text='Tipos de bebidas que puede preparar')),
                ('has_bartender_license', models.BooleanField(default=False, verbose_name='Licencia de barman')),
                ('can_serve_alcohol', models.BooleanField(default=True, verbose_name='Puede servir alcohol')),
                ('total_drinks_prepared', models.PositiveIntegerField(default=0)),
                ('average_prep_time', models.PositiveIntegerField(default=5, help_text='Tiempo promedio en minutos')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal de Bar',
                'verbose_name_plural': 'Personal de Bar',
                'ordering': ['user__first_name'],
                'unique_together': {('restaurant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='KitchenStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, verbose_name='ID de empleado')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('on_break', 'En descanso'), ('busy', 'Ocupado')], default='active', max_length=20)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible para notificaciones')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Recibir emails')),
                ('notification_push', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='Sonido de notificación')),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='Inicio de turno')),
                ('shift_end', models.TimeField(blank=True, null=True, verbose_name='Fin de turno')),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('average_completion_time', models.PositiveIntegerField(default=0, help_text='En minutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('specialties', models.JSONField(blank=True, default=list, help_text="Lista de especialidades: ['pasta', 'pizza', 'carnes']")),
                ('can_modify_prep_time', models.BooleanField(default=False, verbose_name='Puede modificar tiempo de preparación')),
                ('priority_level', models.PositiveIntegerField(default=1, help_text='1=Junior, 2=Senior, 3=Chef')),
                ('total_dishes_prepared', models.PositiveIntegerField(default=0)),
                ('average_prep_time', models.PositiveIntegerField(default=15, help_text='Tiempo promedio en minutos')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal de Cocina',
                'verbose_name_plural': 'Personal de Cocina',
                'ordering': ['-priority_level', 'user__first_name'],
                'unique_together': {('restaurant', 'user')},
            },
        ),
        migrations.CreateModel(
            name='WaiterStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, verbose_name='ID de empleado')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('on_break', 'En descanso'), ('busy', 'Ocupado')], default='active', max_length=20)),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible para notificaciones')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Recibir emails')),
                ('notification_push', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='Sonido de notificación')),
                ('shift_start', models.TimeField(blank=True, null=True, verbose_name='Inicio de turno')),
                ('shift_end', models.TimeField(blank=True, null=True, verbose_name='Fin de turno')),
                ('total_tasks_completed', models.PositiveIntegerField(default=0)),
                ('average_completion_time', models.PositiveIntegerField(default=0, help_text='En minutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('total_orders_served', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.PositiveIntegerField(default=0, help_text='En minutos')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('can_take_orders', models.BooleanField(default=True, verbose_name='Puede tomar pedidos manualmente')),
                ('max_tables_assigned', models.PositiveIntegerField(default=6, verbose_name='Máximo de mesas asignadas')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Garzón',
                'verbose_name_plural': 'Garzones',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('restaurant', 'user')},
            },
        ),
    ]
