# Generated by Django 5.2.2 on 2025-06-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_waiter_average_completion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barstaff',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text="Lista de certificaciones: ['bartender', 'sommelier']"),
        ),
        migrations.AddField(
            model_name='barstaff',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='kitchenstaff',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='waiterstaff',
            name='tips_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de propinas'),
        ),
        migrations.AddField(
            model_name='waiterstaff',
            name='years_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Años de experiencia'),
        ),
        migrations.AlterField(
            model_name='kitchenstaff',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Baja - Cocinero Jr.'), ('medium', 'Media - Cocinero Sr.'), ('high', 'Alta - Chef')], default='medium', max_length=20, verbose_name='Nivel de prioridad'),
        ),
    ]
