# Generated by Django 5.2.2 on 2025-06-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_barstaff_certifications_barstaff_years_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='assigned_waiter_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to='restaurants.waiterstaff', verbose_name='Mesero asignado'),
        ),
        migrations.AlterField(
            model_name='table',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to='restaurants.waiter', verbose_name='Garzón asignado (modelo original)'),
        ),
    ]
