# Generated by Django 5.2.2 on 2025-06-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0002_table_tablescanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.table'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Número de mesa (si aplica) - Deprecated: usar table', max_length=10),
        ),
    ]
