# Generated by Django 5.2.2 on 2025-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_table_alter_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='estimated_prep_time',
            field=models.PositiveIntegerField(default=15, help_text='Tiempo estimado de preparación en minutos para este item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='responsible_area',
            field=models.CharField(blank=True, choices=[('kitchen', 'Cocina'), ('bar', 'Bar'), ('waiter', 'Mesero')], help_text='Área responsable de preparar este item', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de confirmación'), ('confirmed', 'Confirmado por restaurante'), ('preparing_kitchen', 'En preparación - Cocina'), ('cooking', 'Cocinando'), ('plating', 'Emplantando'), ('kitchen_ready', 'Listo en cocina'), ('preparing_bar', 'En preparación - Bar'), ('mixing', 'Preparando bebida'), ('bar_ready', 'Listo en bar'), ('ready', 'Listo para servir'), ('served', 'Servido al cliente'), ('cancelled', 'Cancelado')], default='pending', help_text='Estado específico de este item', max_length=20),
        ),
    ]
