# Generated by Django 5.2.2 on 2025-06-07 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/categories/')),
                ('available_from', models.TimeField(blank=True, null=True, verbose_name='Disponible desde')),
                ('available_until', models.TimeField(blank=True, null=True, verbose_name='Disponible hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.tenant')),
            ],
            options={
                'verbose_name': 'Categoría de Menú',
                'verbose_name_plural': 'Categorías de Menú',
                'ordering': ['order', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(blank=True, max_length=150, verbose_name='Descripción corta')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio con descuento')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Producto destacado')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad en stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/')),
                ('gallery_images', models.JSONField(blank=True, default=list, verbose_name='Galería de imágenes')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorías')),
                ('preparation_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de preparación (minutos)')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetariano')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegano')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Sin gluten')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Picante')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='Alérgenos')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden en categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menucategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.tenant')),
            ],
            options={
                'verbose_name': 'Producto del Menú',
                'verbose_name_plural': 'Productos del Menú',
                'ordering': ['category__order', 'order', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MenuAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addon_type', models.CharField(choices=[('INGREDIENT', 'Ingrediente extra'), ('SIDE', 'Acompañamiento'), ('SAUCE', 'Salsa'), ('DRINK', 'Bebida'), ('OTHER', 'Otro')], default='INGREDIENT', max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del extra')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('max_quantity', models.PositiveIntegerField(default=3, verbose_name='Cantidad máxima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_addons', to='restaurants.tenant')),
                ('menu_items', models.ManyToManyField(related_name='available_addons', to='menu.menuitem', verbose_name='Productos compatibles')),
            ],
            options={
                'verbose_name': 'Extra/Complemento',
                'verbose_name_plural': 'Extras/Complementos',
                'ordering': ['addon_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modifier_type', models.CharField(choices=[('REMOVE', 'Quitar ingrediente'), ('ADD', 'Agregar extra'), ('STYLE', 'Estilo de preparación'), ('TEMPERATURE', 'Temperatura'), ('OTHER', 'Otro')], default='REMOVE', max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del modificador')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Modificador de precio (+/-)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_items', models.ManyToManyField(related_name='available_modifiers', to='menu.menuitem', verbose_name='Productos compatibles')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_modifiers', to='restaurants.tenant')),
            ],
            options={
                'verbose_name': 'Modificador',
                'verbose_name_plural': 'Modificadores',
                'ordering': ['modifier_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_type', models.CharField(choices=[('SIZE', 'Tamaño'), ('TYPE', 'Tipo'), ('STYLE', 'Estilo'), ('OTHER', 'Otro')], default='SIZE', max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la variante')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Modificador de precio (+/-)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Variante por defecto')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_variants', to='restaurants.tenant')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['variant_type', 'order', 'name'],
                'unique_together': {('menu_item', 'name')},
            },
        ),
    ]
