# Generated by Django 5.2.2 on 2025-06-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('food', 'Comida'), ('drink', 'Bebida'), ('both', 'Ambos')], default='food', help_text='Determina qué personal debe preparar este item', max_length=10, verbose_name='Tipo de item'),
        ),
    ]
